version: 2.1

jobs:
  node-job:
    docker:
      - image: timbru31/java-node:latest
    steps:
      - checkout
      - run:
          name: Get access
          command: chmod 777  /root
      - run:
          name: Update dependencies
          command: apt update && apt upgrade -y
      - run:
          name: Install libs
          command: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
      - run:
          name: Update cypress
          command: npm install cypress --save-dev
      - run:
          name: Install unzip
          command: apt-get install -y unzip
      - run:
          name: Install Allure
          command: |
            curl -sSL https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip -o allure.zip
            unzip allure.zip -d /opt/allure
            ln -s /opt/allure/allure-2.19.0/bin/allure /usr/bin/allure
      - run:
          name: install all
          command: npm i
      - run:
          name: run tests
          command: npx cypress run || true
      - run:
          name: generate report
          command: npm run allure:report
      - store_artifacts:
          path: allure-report
          destination: CypressReport


workflows:
  build-and-test:
    jobs:
      - node-job